### PR TITLE
Add docs for v2 API 

### PR DESCRIPTION
**Pull request by mrdavidlaing**
Add docs for v2 API based on https://gist.github.com/testobsessed/ad4fbbbd6ff3cc6f0f4d

### CODE REVIEW

**Comment by scottfrederick** [comment]
IMO, this is in the wrong place in the docs heirarchy. I think the CC API docs belongs in Using instead of Running, since the API is likely to be used by devs who are only consuming a platform. APIs for components besides CC should be in Running.

**Comment by andypiper** [comment]
Well @mreider laid out the TOC I think. I'm somewhat inclined to agree with you @scottfrederick but I'm not sure we should be separating APIs into different sections across the docs overall. How about a "Reference" section which covers Architecture and API?

**Comment by mrdavidlaing** [comment]
@scottfrederick @andypiper - As suggested, a reference section, with links from both Using & Running to the API docs in the reference section.

What do you think?

**Comment by mreider** [comment]
Seems fine. We can always change it later.

**Comment by scottfrederick** [comment]
Yes, @mreider laid out the TOC and the heirarchy, but it will change and evolve as we build out the content. 

I'm not sure about internal and external API docs yet. The CC API is used as a way for devs to build custom apps against the platform, while other APIs are for components to communicate with each other. This setup is fine for now, like Matt said we can adjust as we go.

I'm working on another idea for API docs that would automate the process a bit more. The content checked in here looks like it is generated, but 80% of that content is hand-written and not as usable as I think it could be. Hopefully I can get some things wrapped up and get back to that soon.

**Pull request merged**
