### PR TITLE
Memcached Cloud Docs

### PR DESCRIPTION
**Pull request by kehati**
Adding docs for our new Memcached Cloud service.

### CODE REVIEW

**Comment by mpmcgarry** [comment]
Kehati, are you able to get yourself added to your company's CLA?

**Comment by kehati** [comment]
Hi, 

How should I get added to my organizations CLA? Will putting my email (matan@garantiadata.com) under the 'Company Mailing Address' section do the trick?
Or should I fill an additional individual CLA (less preferred option)?

Thanks!

**Comment by shalako** [comment]
Helllo @kehati, 
You just need to be a public member of your organization's Github org. Currently there are no public members at https://github.com/GarantiaData?tab=members.

**Comment by kehati** [comment]
Added myself as a public member.
Thanks.

**Pull request merged**
