### PR TITLE
Install CF to OpenStack

### PR DESCRIPTION
**Pull request by drnic**
Complete instructions for installing a small, DNS-based
Cloud Foundry deployment to OpenStack.

### CODE REVIEW

**Comment by drnic** [comment]
This is merged but not appearing in http://docs.cloudfoundry.com/docs/running/deploying-cf/openstack/install_cf_openstack.html can you trigger the build?

**Comment by jbayer** [comment]
@mreider typically does this and he's traveling in New York visiting family and it's Father's Day. It'll likely get published Monday.

Happy Father's Day Nic!

**Comment by drnic** [comment]
Ok. Perhaps create a Jenkins task to auto-deploy on changes to cf-docs master branch and @mreider can holiday forever :)

​I mistakingly tweeted the docs yesterday because I saw the branch was merged :) I just assumed we were on GitHub pages I guess or similar. Oops :)

## 

Dr Nic Williams
Stark & Wayne LLC - the consultancy for Cloud Foundry
http://starkandwayne.com
+1 415 860 2185
twitter: drnic

**Comment by scottfrederick** [comment]
The docs are published, they should show up in a few minutes.

We usually publish the docs from source every few day if there are changes
going in. If we know a set of PRs complete a task, we can publish right
after we merge. If you put a comment in a PR like "please publish the docs
after this merge" then we will certainly do that. The publish step is a
simple script that is run, but we prefer to keep it manual for now.

Scott

**Comment by drnic** [comment]
## Why the preference?

Dr Nic Williams
Stark & Wayne LLC - the consultancy for Cloud Foundry
http://starkandwayne.com
+1 415 860 2185
twitter: drnic

**Comment by scottfrederick** [comment]
To date, the docs have undergone a few rounds of re-structuring and we've
coordinated changes across multiple people. It is easier for us to manually
publish after an atomic set of changes than to have some half-baked changes
being published. This should be settling down after launch. When the
changes are more incremental in nature then automated deployment will make
more sense.

**Comment by drnic** [comment]
## Gotcha, thanks.

Dr Nic Williams
Stark & Wayne LLC - the consultancy for Cloud Foundry
http://starkandwayne.com
+1 415 860 2185
twitter: drnic

**Pull request merged**
