### PR TITLE
add a note pointing out a gateway will be a broker in the future

### PR DESCRIPTION
**Pull request by fearoffish**
As per our discussion over at https://github.com/cloudfoundry/cf-docs/pull/160 I propose a simple change for now, otherwise it's very confusing.

### CODE REVIEW

**Comment by fearoffish** [comment]
How do I get this bot to leave me alone :(

cfdreddbot wrote:

**Comment by cdavisafc** [comment]
Much better already.  Thanks!

I hear you can get the bot to leave you alone with proper configurations - Scott Fredrick did it recently - he likely has the details.

**Comment by fearoffish** [comment]
By proper configuration, do you mean my email and github username? They 
should match what my contributor setup is. :(

Cornelia Davis wrote:

**Comment by shalako** [comment]
Hello again, Jamie. 

I committed a tweak of your suggested changes, along with a few others. The breadcrumbs were broken and the gateway definition was incomplete. 

If this looks good then then this PR can be closed: http://docs.cloudfoundry.com/docs/running/deploying-cf/services/

**Comment by ryantang** [comment]
@fearoffish — I updated and kicked the bot, so it should be leaving you alone now.  

@shalako — Thanks updating the docs and incorporating @fearoffish's clarifications.

Ryan

**Pull request closed without merging**
