### PR TITLE
Service Broker API 2.1 doc updates

### PR DESCRIPTION
**Pull request by moonmaster9000**

### CODE REVIEW

**Comment by moonmaster9000** [comment]
I work for Pivotal Labs.

**Comment by shalako** [comment]
This PR should be rebased against master. These pages have been reformatted quite a bit since this was forked.

**Comment by xchoi** [comment]
hold on a second w/r/t this, fixing up a few things.

**Comment by xchoi** [comment]
things got ugly here, made a new branch with cherry-picked commits from here. Closing.

**Pull request closed without merging**
