### PR TITLE
cleanup and clarify

### PR DESCRIPTION
**Pull request by fearoffish**
I thought this version of the documentation read better, so here you go.

### CODE REVIEW

**Comment by drnic** [comment]
@fearoffish looks good to me

**Comment by drnic** [comment]
@scottfrederick can you please ping me or reply to this PR when you've deployed to production; then I'll release a blog post.

**Comment by scottfrederick** [comment]
@mpmcgarry is doing the publishing these days. If you are at Howard you can ping her in person.

**Comment by cdavisafc** [comment]
I wasn't able to find this page on docs.cloudfoundry.com - is it in prod?

Anyway, I would suggest that we not post verbiage that is v1 anymore.  This discussion (https://groups.google.com/a/cloudfoundry.org/forum/#!msg/vcap-dev/S3PmT26LqZw/Y9Y7D40H5NcJ) discusses, and get community support, for using the term "service broker" for what used to be "service gateway." Let's not publish things anymore that say "we are using V1 terminology."

**Comment by drnic** [comment]
Cornelia, but that code doesn't exist yet. This is documentation for services that finally work. Please don't suggest we don't document them because we're now talking about changing terminology in future code.

```
"V1" is the services API version; not CF version.

--
```

Dr Nic Williams
Stark & Wayne LLC - the consultancy for Cloud Foundry
http://starkandwayne.com
+1 415 860 2185
twitter: drnic

**Comment by cdavisafc** [comment]
I'm not.

I see the challenge, the existing "code" (jobs/packages) has the word
"gateway" in it. But those are just names. Perhaps the text can use the
term "service broker" when it is used for the concept, and use the formal
names, i.e. postgresql_gateway_ng job, when referring to the specific
artifacts in the release.  With a short section that explains the "gateway"
--> "broker" change.  I'm simply looking to avoid perpetuating the very
confusion that Shannon's email addresses.

**Comment by drnic** [comment]
Ok I'll re-read the doc and look at rewording gateway -> broker or co-wording it; since "gateway" is literally what these things are called in all source code at the moment.

We'll need a way to document two sets of services once new v2 API services come out. Initially there'll only be a MySQL service implemented for the v2 API; so we'll want to keep the documentation for the v1 services

**Comment by drnic** [comment]
... v1 API services until they are no longer used ( hopefully we all write a migration path for each service).

**Comment by fearoffish** [comment]
I've had a go at re-wording it, and actually I'd say it's impossible until the code and manifests require the word 'broker'. It's totally confusing otherwise. I've opted for just noting that it is changing rather than trying to ask the user to put details in a 'postgresql_gateway' in the 'gateways' job...whilst telling them it's a broker.

**Comment by drnic** [comment]
Yeah I'm concerned about the doc becoming in comprehensible by us worrying about the future terminology changes today.

```
--
```

Dr Nic Williams
Stark & Wayne LLC - the consultancy for Cloud Foundry
http://starkandwayne.com
+1 415 860 2185
twitter: drnic

**Comment by fearoffish** [comment]
I've had a go at re-wording it, and actually I'd say it's impossible 
until the code and manifests require the word 'broker'. It's totally 
confusing otherwise. I've opted for just noting that it is changing 
rather than trying to ask the user to put details in a 
'postgresql_gateway' in the 'gateways' job...whilst telling them it's a 
broker.

https://github.com/cloudfoundry/cf-docs/pull/161

Dr Nic Williams wrote:

**Pull request merged**
