### PR TITLE
updates to services index pages

### PR DESCRIPTION
**Pull request by shalako**

### CODE REVIEW

**Comment by testobsessed** [comment]
@shalako would you be willing to submit this pull request against the new repo?

**Comment by shalako** [comment]
Honestly the directory structure of cloudfoundry/docs-services is confusing enough that I'm not comfortable doing this yet. There are three different index files when there should only be one; index.html, /services/index.html, and /services/services/index.html. Also the docs-services repo does not include recent changes which have been merged to cf-docs. I don't want us to get into a situation like we've been in before where new commits are merged before older ones, resulting in overwritten/missing work.

**Comment by testobsessed** [comment]
If you're not comfortable as the author, we have no hope of being able to correctly place your content in the new structure. This repo is deprecated. How about if a docs person pairs with you on getting the content changes put into place?

**Comment by shalako** [comment]
Docs team put together the new system, set up all all new dirs, and has been applying updates for PRs made to cf-docs. I assume they know where and why better that me. 

However, working with a doc team member would be great, I expect they can answer the questions I have. 

On Feb 14, 2014, at 11:34 AM, Elisabeth Hendrickson notifications@github.com wrote:

If you're not comfortable as the author, we have no hope of being able to correctly place your content in the new structure. This repo is deprecated. How about if a docs person pairs with you on getting the content changes put into place?

**Comment by animatedmax** [comment]
Closed. Updated information incorporated into new document repositories,

**Pull request closed without merging**
