### PR TITLE
grammatical fix

### PR DESCRIPTION
**Pull request by sweetleon**

### CODE REVIEW

**Comment by jbayer** [comment]
@sweetleon thanks for the doc correction! are you able to sign our CLA so we can process this Pull Request give you credit for this contribution?

**Comment by sweetleon** [comment]
Hi James,

I work for Pivotal Labs. Does that suffice?

Cheers,
Lenny

**Comment by jbayer** [comment]
yes, it does! if you put yourself as a public member here: https://github.com/orgs/pivotal/members then you should not be nagged in the future.

**Comment by jbayer** [comment]
@kimahoff this should be good to merge

**Comment by kimahoff** [comment]
Thanks for the edit!

**Pull request merged**
