### PR TITLE
Update SendGrid example to include vcapenv

### PR DESCRIPTION
**Pull request by motdotla**
This gives an example of using SendGrid combined with vcapenv to make it really simple to setup (without directly typing in your credentials).

### CODE REVIEW

**Comment by motdotla** [comment]
I work at SendGrid.

**Comment by testobsessed** [comment]
Thank you @scottmotte!

**Comment by andypiper** [comment]
Just a question, why not use either cf-runtime-lib or spring-cloud instead of this library?

**Comment by motdotla** [comment]
Spring-cloud is only for spring apps correct? cf-runtime-lib, I'm not aware of, what does that do?

**Comment by mstine** [comment]
No...spring-cloud "core" and "cloudfoundry-connector" - which are all you
need here - have no deps on Spring and can be used from "plain old Java
apps." See
https://github.com/spring-projects/spring-cloud/blob/master/README.md#non-spring-apps
.

Matt Stine | Community Engineer, Cloud Foundry | Pivotal
901-493-5546 | Skype: mstine1978 | mstine@goPivotal.com

goPivotal.com

**Comment by motdotla** [comment]
Nice. What would the code example look like for that?

**Comment by mstine** [comment]
Basically what you see here...

https://github.com/spring-projects/spring-cloud/blob/master/core/README.md#usage-pattern-application-developers

Matt Stine | Community Engineer, Cloud Foundry | Pivotal
901-493-5546 | Skype: mstine1978 | mstine@goPivotal.com

goPivotal.com

**Comment by shalako** [comment]
@andypiper Looks like @mstine has it covered. @scottfrederick might also be interested.

**Comment by scottfrederick** [comment]
The SendGrid sample app we have in our cloudfoundry-samples repo uses Spring Cloud already, albeit with the Spring support and JavaMail: https://github.com/cloudfoundry-samples/spring-sendgrid/blob/master/src/main/java/org/cloudfoundry/samples/email/config/app/AppCloudConfig.java#L14.

To support the SendGrid Java API instead of JavaMail, we would need to write a few small adapter classes to create the right objects. One part of the JavaMail creation is here, as an example: https://github.com/spring-projects/spring-cloud/blob/master/cloudfoundry-connector/src/main/java/org/springframework/cloud/cloudfoundry/SmtpServiceInfoCreator.java. 

`cf-runtime-lib` was the predecessor to Spring Cloud.

**Comment by andypiper** [comment]
I guess my concern is introducing too many differing helper libraries in the core docs, would be nice to stick with one.

**Comment by motdotla** [comment]
Scott. What does an end to end completed bit of code look like using that connector? Can you quickly paste that code here. I'd like to see how easy it is for a newbie like me. For a new Java person like me this setup currently seems quite difficult. 

—

**Comment by scottfrederick** [comment]
@scottmotte I'm working up a Spring Cloud connector for a different use case, I can at least mock up one for the SendGrid Java API and then we can talk about it.

**Comment by motdotla** [comment]
That'd be awesome. Code wins debates in my book. So if that code is quite easy and can support everything sendgrid-java does to the point that a beginner can copy and paste - then I think going that route is the way to go. 

Ultimately, though this stuff is your guys call and I will help however I can. As a beginner Java guy I don't know as much as you.

**Pull request merged**
