### PR TITLE
Java and Java Buildpack Documentation

### PR DESCRIPTION
**Pull request by nebhale**
Previously, much of the Java and Java Buildpack documentation in docs.cloudfoundry.com was out of date.  This change updates that documentation to better represent modern-day capabilities.

[#64675106]

### CODE REVIEW

**Comment by nebhale** [comment]
Just a quick note that the issue created by cf-gitbot isn't actually publicly visible...

**Comment by kimahoff** [comment]
Thanks for all the updates!

**Comment by nebhale** [comment]
My pleasure.

**Comment by rmorgan** [comment]
Very nice, thanks @nebhale !

**Comment by scottfrederick** [comment]
@nebhale Several pages refer to spring-cloud components with version 1.0.2, but 0.9.5 is the latest released version[1][2]. 1.0.2 is correct for cloudfoundry-client-lib. 

[1] http://repo.spring.io/milestone/org/springframework/cloud/spring-service-connector/ 
[2] http://repo.spring.io/milestone/org/springframework/cloud/cloudfoundry-connector/

**Comment by nebhale** [comment]
@scottfrederick I'll get in a subsequent PR to fix those up.

**Pull request merged**
