### PR TITLE
Link to "deploy services" page broken from home

### PR DESCRIPTION
**Pull request by drnic**
I thinik it was caused by https://github.com/cloudfoundry/cf-docs/commit/5a98739558b8214a400d7cc347b1f0b17a3066e7#source/docs/running/deploying-cf/services/index.html.md

### CODE REVIEW

**Comment by mpmcgarry** [comment]
Is there a broken link on http://docs.cloudfoundry.com/?  We do not have a "deploy services" page, as far as I know.  What is the URL of target page?  thanks.

m

**Comment by drnic** [comment]
Sorry, its the "Adding Services" link which goes to
http://docs.cloudfoundry.com/docs/running/deploying-cf/services/adding-services.htmlcurrently
instead of
http://docs.cloudfoundry.com/docs/running/deploying-cf/services/

**Comment by drnic** [comment]
I should have just fixed it; but didn't want to forget :)

**Comment by drnic** [comment]
Fix attached to ticket.

**Comment by mpmcgarry** [comment]
David Stevenson updated the index page and the link is now fixed.  I will close this pull request.

**Pull request closed without merging**
