### PR TITLE
Load Impact documentation updates

### PR DESCRIPTION
**Pull request by robingustafsson**
I've updated the Load Impact documentation. Let me know if there's anything that needs to be changed. Thanks.

### CODE REVIEW

**Comment by shalako** [comment]
This looks great, and can be merged as soon as the CLA is confirmed.

**Comment by robingustafsson** [comment]
Great, CLA has been signed and sent.

**Comment by andreasmaier** [comment]
@robingustafsson Thanks for the quick response. Unfortunately we didn't receive the CLA. Can you please resend it to contributors@cloudfoundry.org ?

**Comment by robingustafsson** [comment]
@AndreasMaier Sure, you should have it in the contributors@cloudfoundry.org inbox now :-)

**Pull request merged**
